version: '3.8'

services:
  omrchecker:
    build:
      context: .
      dockerfile: Dockerfile
    image: omrchecker:latest
    container_name: omrchecker-app
    ports:
      - "7860:7860"
    volumes:
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs
      - ./fonts:/app/fonts
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
